server:
  port: 7900
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #eureka注册中心剔除间隔
  instance:
    lease-expiration-duration-in-seconds: 1  #eureka心跳发送间隔
    lease-renewal-interval-in-seconds: 2   #eureka注册中心剔除间隔
spring:
  application:
    name: provider
#management:
#  security:
#  enabled: false #关掉安全认证

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

